name: Deploy Payuee to Oracle Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 84.8.135.142
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            bash /home/ubuntu/deploy.sh

